### ISSUE TITLE
Add linting on js files

### ISSUE THREAD

**Issue by jchavarri** [jchavarri/rroo#14]
There are some basic mistakes that can happen all the time in `.js` files. Adding eslint (or typescript?) would help mitigate that.

**Comment by jchavarri** [comment]
We could also use BuckleScript (kidding / not kidding ) 😄

**Comment by benschinn** [comment]
lol, I kinda like the idea of using BuckleScript. that would take care of both linting and type.

**Comment by jchavarri** [comment]
Yeah 😄 I have been thinking more, and if extra tooling is going to be added, we could just as well use jsoo [`Js` module](http://ocsigen.org/js_of_ocaml/3.1.0/api/Js), and ppx (`obj##.property`, `obj##method`), which has quite good support to deal with JS data types (actually BuckleScript was inspired from it in many ways).

As an example, this:

https://github.com/jchavarri/rroo/blob/4aac16dac3c6fed395805b33c4e0ae6035a27ce6/lib/InteropUtils.js#L11-L13

would become this:

```reason
Js.Opt.to_option
```

😂 

Maybe a small experiment with `useState` for example would throw more light, but it seems like the simplest path forward. If that was the case the `external` go away and are replaced with regular `let` where the converted logic for each function would go.

**Comment by benschinn** [comment]
I wish I had more experience with jsoo to give constructive input. Although it's very fascinating to learn where bs drew some inspiration. 😅

So if I understand correctly, if we decided to just use the jsoo, `lib/React.js` would be replaced with one jsoo ffi implementation? Any no need for `external`s ?

**Comment by jchavarri** [comment]
@benschinn Exactly! No need for `.js` files anymore.
