### ISSUE TITLE
Error when running example

### ISSUE THREAD

**Issue by benschinn** [jchavarri/rroo#8]
I successfully installed both npm and opam dependencies. Joo is generating js files. I am getting an error when I open `bin/index.html`. 

<img width="528" alt="Screen Shot 2019-05-28 at 10 44 44 AM" src="https://user-images.githubusercontent.com/21044999/58496973-2fb42e80-8138-11e9-8d15-f15d509ce2af.png">

This is where the error is in `App.bc.js`:

<img width="841" alt="Screen Shot 2019-05-28 at 10 55 20 AM" src="https://user-images.githubusercontent.com/21044999/58497074-5d00dc80-8138-11e9-8bbc-22ce1ffaf17c.png">

**Comment by jchavarri** [comment]
hey!

Yeah, i'm still figuring out the bundling / JS dependencies part in jsoo.

There is a workaround though, that involve updating the files in `node_modules`, see https://github.com/jchavarri/rroo#uncaught-typeerror-cannot-set-property-react-of-undefined.

**Comment by benschinn** [comment]
Got it! Sorry I missed that section in the readme! ^^;
